# NHL Draft Analysis

This notebook loads the draft scores produced by formula.ipynb, applies 
franchise consolidation, adds team colors, and exports clean CSVs for 
the Tableau dashboard.

## Setup

In [1]:
import pandas as pd

df = pd.read_csv('../data/outputs/draft_scores_adjusted.csv')
print(f"Loaded {len(df)} rows")
df.head()

Loaded 2484 rows

,draft_year,round,pick_number,drafted_by,player_name,position,games_played,points,performance_score,hindsight_rank,plus_minus
0,2005,1,1,Pittsburgh,Sidney Crosby,C,1408.0,1746.0,5406.34,1,0
1,2005,1,2,Anaheim,Bobby Ryan,R,866.0,569.0,2169.01,9,-7
2,2005,1,3,Carolina,Jack Johnson,D,1228.0,342.0,2011.18,12,-9
3,2005,1,4,Minnesota,Benoit Pouliot,L,625.0,263.0,1227.27,21,-17
4,2005,1,6,Columbus,Gilbert Brule,C,299.0,95.0,516.55,39,-33

## Team Rankings

Overall team draft rankings from 2005 to 2017, measured by cumulative 
plus/minus across all picks and all drafts.

In [2]:
team_rankings = df.groupby('drafted_by').agg(
    total_plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_rankings = team_rankings.sort_values('total_plus_minus', ascending=False).reset_index(drop=True)
team_rankings.index += 1
team_rankings.columns = ['team', 'total_plus_minus', 'total_picks', 'avg_per_pick']

print("NHL Team Draft Rankings 2005-2017")
print(team_rankings.to_string())

NHL Team Draft Rankings 2005-2017
            team  total_plus_minus  total_picks  avg_per_pick
1       San Jose              2088           81         25.78
2    Los Angeles              1971           88         22.40
3        Toronto              1631           87         18.75
4      Tampa Bay              1488           86         17.30
5   Philadelphia              1400           78         17.95
6         Ottawa              1313           78         16.83
7     Washington              1217           78         15.60
8       Columbus              1179           85         13.87
9      Nashville              1023           85         12.04
10    New Jersey               986           84         11.74
11        Dallas               931           75         12.41
12    Pittsburgh               927           71         13.06
13       Detroit               913           87         10.49
14  NY Islanders               897           88         10.19
15        Boston               893           78         11.45
16     Minnesota               812           73         11.12
17      Winnipeg               723           86          8.41
18      Carolina               705           81          8.70
19       Chicago               623          104          5.99
20    NY Rangers               561           77          7.29
21       Anaheim               558           78          7.15
22      Edmonton               501           86          5.83
23       Calgary               497           77          6.45
24       Florida               488           86          5.67
25     St. Louis               453           89          5.09
26       Buffalo               423           92          4.60
27      Montreal               419           80          5.24
28      Colorado               368           79          4.66
29     Vancouver               283           75          3.77
30         Vegas               104           10         10.40
31       Arizona              -201           82         -2.45

## Consistency Analysis

Team plus/minus broken down by draft year. Reveals whether a team's 
overall ranking is driven by consistent performance or a few standout 
draft classes.

In [3]:
team_by_year = df.groupby(['drafted_by', 'draft_year']).agg(
    plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_by_year = team_by_year.rename(columns={'drafted_by': 'team'})

print(f"team_by_year shape: {team_by_year.shape}")
team_by_year.head(20)

team_by_year shape: (391, 5)

       team  draft_year  plus_minus  total_picks  avg_plus_minus_per_pick
0   Anaheim        2005         -20            5                    -4.00
1   Anaheim        2006          85            5                    17.00
2   Anaheim        2007         -41            6                    -6.83
3   Anaheim        2008         -57            9                    -6.33
4   Anaheim        2009         -12            6                    -2.00
5   Anaheim        2010         128            8                    16.00
6   Anaheim        2011         205            6                    34.17
7   Anaheim        2012         115            7                    16.43
8   Anaheim        2013         -46            5                    -9.20
9   Anaheim        2014         187            5                    37.40
10  Anaheim        2015           1            6                     0.17
11  Anaheim        2016          35            6                     5.83
12  Anaheim        2017         -22            4                    -5.50
13  Arizona        2005          99            4                    24.75
14  Arizona        2006         106            7                    15.14
15  Arizona        2007        -120            5                   -24.00
16  Arizona        2008         -64            8                    -8.00
17  Arizona        2009         -32            5                    -6.40
18  Arizona        2010         -93            3                   -31.00
19  Arizona        2011        -138            8                   -17.25

## Round Analysis

Team plus/minus broken down by draft round. Reveals whether certain 
teams excel at finding late round steals or consistently capitalize 
on early round picks.

In [4]:
team_by_round = df.groupby(['drafted_by', 'round']).agg(
    plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_by_round = team_by_round.rename(columns={'drafted_by': 'team'})

print(f"team_by_round shape: {team_by_round.shape}")
team_by_round.head(20)
print(team_by_round.to_string())

team_by_round shape: (216, 5)
             team  round  plus_minus  total_picks  avg_plus_minus_per_pick
0         Anaheim      1        -232           15                   -15.47
1         Anaheim      2        -270           16                   -16.88
2         Anaheim      3         -49           12                    -4.08
3         Anaheim      4         207           10                    20.70
4         Anaheim      5         354           12                    29.50
5         Anaheim      6         234            7                    33.43
6         Anaheim      7         314            6                    52.33
7         Arizona      1        -402           18                   -22.33
8         Arizona      2        -294           13                   -22.62
9         Arizona      3        -117           14                    -8.36
10        Arizona      4         201            9                    22.33
11        Arizona      5         261           11                    23.73
12        Arizona      6           0            6                     0.00
13        Arizona      7         150           11                    13.64
14         Boston      1        -302           14                   -21.57
15         Boston      2        -262           15                   -17.47
16         Boston      3          63            6                    10.50
17         Boston      4         258            9                    28.67
18         Boston      5         394           11                    35.82
19         Boston      6         495           11                    45.00
20         Boston      7         247           12                    20.58
21        Buffalo      1        -296           15                   -19.73
22        Buffalo      2        -362           15                   -24.13
23        Buffalo      3         -65           14                    -4.64
24        Buffalo      4         251           10                    25.10
25        Buffalo      5         276           14                    19.71
26        Buffalo      6         363            8                    45.38
27        Buffalo      7         256           16                    16.00
28        Calgary      1        -348           12                   -29.00
29        Calgary      2        -112            8                   -14.00
30        Calgary      3        -110           12                    -9.17
31        Calgary      4         406           12                    33.83
32        Calgary      5          95            9                    10.56
33        Calgary      6         339           10                    33.90
34        Calgary      7         227           14                    16.21
35       Carolina      1        -271           12                   -22.58
36       Carolina      2          11           13                     0.85
37       Carolina      3         -53           13                    -4.08
38       Carolina      4         309           14                    22.07
39       Carolina      5         187           10                    18.70
40       Carolina      6         295           10                    29.50
41       Carolina      7         227            9                    25.22
42        Chicago      1        -187           12                   -15.58
43        Chicago      2        -433           19                   -22.79
44        Chicago      3         -82           15                    -5.47
45        Chicago      4         353           15                    23.53
46        Chicago      5         337           14                    24.07
47        Chicago      6         438           17                    25.76
48        Chicago      7         197           12                    16.42
49       Colorado      1        -222           11                   -20.18
50       Colorado      2        -421           17                   -24.76
51       Colorado      3           4            8                     0.50
52       Colorado      4          96           11                     8.73
53       Colorado      5         307            9                    34.11
54       Colorado      6         334           11                    30.36
55       Colorado      7         270           12                    22.50
56       Columbus      1        -320           14                   -22.86
57       Columbus      2        -322           14                   -23.00
58       Columbus      3         100            8                    12.50
59       Columbus      4         363           12                    30.25
60       Columbus      5         205           13                    15.77
61       Columbus      6         672           12                    56.00
62       Columbus      7         481           12                    40.08
63         Dallas      1        -310           11                   -28.18
64         Dallas      2         -92           12                    -7.67
65         Dallas      3           6           11                     0.55
66         Dallas      4         212            9                    23.56
67         Dallas      5         778           19                    40.95
68         Dallas      6         211            8                    26.38
69         Dallas      7         126            5                    25.20
70        Detroit      1         -96            8                   -12.00
71        Detroit      2         -11           16                    -0.69
72        Detroit      3         -21           13                    -1.62
73        Detroit      4         314            9                    34.89
74        Detroit      5         271           13                    20.85
75        Detroit      6         211           13                    16.23
76        Detroit      7         245           15                    16.33
77       Edmonton      1        -170           15                   -11.33
78       Edmonton      2        -278           10                   -27.80
79       Edmonton      3        -149           15                    -9.93
80       Edmonton      4         288           16                    18.00
81       Edmonton      5         147           11                    13.36
82       Edmonton      6         411           11                    37.36
83       Edmonton      7         252            8                    31.50
84        Florida      1        -221           14                   -15.79
85        Florida      2        -399           12                   -33.25
86        Florida      3         -53           15                    -3.53
87        Florida      4         219           16                    13.69
88        Florida      5         213            9                    23.67
89        Florida      6         293           11                    26.64
90        Florida      7         436            9                    48.44
91    Los Angeles      1         -69           10                    -6.90
92    Los Angeles      2        -163           14                   -11.64
93    Los Angeles      3         103           11                     9.36
94    Los Angeles      4         491           13                    37.77
95    Los Angeles      5         531           14                    37.93
96    Los Angeles      6         294           11                    26.73
97    Los Angeles      7         784           15                    52.27
98      Minnesota      1        -253           12                   -21.08
99      Minnesota      2        -107           10                   -10.70
100     Minnesota      3          29            5                     5.80
101     Minnesota      4         187           12                    15.58
102     Minnesota      5         368            9                    40.89
103     Minnesota      6          75           10                     7.50
104     Minnesota      7         513           15                    34.20
105      Montreal      1        -279           12                   -23.25
106      Montreal      2        -185           11                   -16.82
107      Montreal      3         -92           14                    -6.57
108      Montreal      4          56           10                     5.60
109      Montreal      5         304           14                    21.71
110      Montreal      6         272            8                    34.00
111      Montreal      7         343           11                    31.18
112  NY Islanders      1        -271           15                   -18.07
113  NY Islanders      2        -199            9                   -22.11
114  NY Islanders      3        -255           14                   -18.21
115  NY Islanders      4         327           13                    25.15
116  NY Islanders      5         364           12                    30.33
117  NY Islanders      6         693           13                    53.31
118  NY Islanders      7         238           12                    19.83
119    NY Rangers      1        -186           10                   -18.60
120    NY Rangers      2        -107            8                   -13.38
121    NY Rangers      3         -80           15                    -5.33
122    NY Rangers      4         215           12                    17.92
123    NY Rangers      5         160           14                    11.43
124    NY Rangers      6         419           10                    41.90
125    NY Rangers      7         140            8                    17.50
126     Nashville      1        -115            9                   -12.78
127     Nashville      2        -139           13                   -10.69
128     Nashville      3         119           14                     8.50
129     Nashville      4         333           15                    22.20
130     Nashville      5         320           10                    32.00
131     Nashville      6         174           13                    13.38
132     Nashville      7         331           11                    30.09
133    New Jersey      1        -236           10                   -23.60
134    New Jersey      2         -86           11                    -7.82
135    New Jersey      3         152           16                     9.50
136    New Jersey      4         293           12                    24.42
137    New Jersey      5         451           10                    45.10
138    New Jersey      6         306           13                    23.54
139    New Jersey      7         106           12                     8.83
140        Ottawa      1        -287           14                   -20.50
141        Ottawa      2        -164            9                   -18.22
142        Ottawa      3          35            8                     4.38
143        Ottawa      4         544           18                    30.22
144        Ottawa      5         411            9                    45.67
145        Ottawa      6         265            9                    29.44
146        Ottawa      7         509           11                    46.27
147  Philadelphia      1        -164           13                   -12.62
148  Philadelphia      2        -231            9                   -25.67
149  Philadelphia      3         144           11                    13.09
150  Philadelphia      4         164           11                    14.91
151  Philadelphia      5         419           10                    41.90
152  Philadelphia      6         720           13                    55.38
153  Philadelphia      7         348           11                    31.64
154    Pittsburgh      1        -226            9                   -25.11
155    Pittsburgh      2        -212            9                   -23.56
156    Pittsburgh      3         233           10                    23.30
157    Pittsburgh      4         208           10                    20.80
158    Pittsburgh      5         373           12                    31.08
159    Pittsburgh      6         247           13                    19.00
160    Pittsburgh      7         304            8                    38.00
161      San Jose      1        -154           10                   -15.40
162      San Jose      2        -184           12                   -15.33
163      San Jose      3        -101            5                   -20.20
164      San Jose      4         113            7                    16.14
165      San Jose      5         545           16                    34.06
166      San Jose      6         706           14                    50.43
167      San Jose      7        1163           17                    68.41
168     St. Louis      1         -44           15                    -2.93
169     St. Louis      2        -392           17                   -23.06
170     St. Louis      3          46           10                     4.60
171     St. Louis      4         204           14                    14.57
172     St. Louis      5         215            9                    23.89
173     St. Louis      6         424           14                    30.29
174     St. Louis      7           0           10                     0.00
175     Tampa Bay      1        -208           11                   -18.91
176     Tampa Bay      2        -236           14                   -16.86
177     Tampa Bay      3          71           13                     5.46
178     Tampa Bay      4         352           12                    29.33
179     Tampa Bay      5          88            6                    14.67
180     Tampa Bay      6         734           13                    56.46
181     Tampa Bay      7         687           17                    40.41
182       Toronto      1        -234           11                   -21.27
183       Toronto      2        -308           11                   -28.00
184       Toronto      3         -83           11                    -7.55
185       Toronto      4         190           11                    17.27
186       Toronto      5         378           15                    25.20
187       Toronto      6         637           15                    42.47
188       Toronto      7        1051           13                    80.85
189     Vancouver      1        -419           14                   -29.93
190     Vancouver      2        -192            7                   -27.43
191     Vancouver      3         -20            7                    -2.86
192     Vancouver      4          26            7                     3.71
193     Vancouver      5         382           14                    27.29
194     Vancouver      6         272           13                    20.92
195     Vancouver      7         234           13                    18.00
196         Vegas      1         -32            3                   -10.67
197         Vegas      2          11            2                     5.50
198         Vegas      3           4            1                     4.00
199         Vegas      5           0            2                     0.00
200         Vegas      6           0            1                     0.00
201         Vegas      7         121            1                   121.00
202    Washington      1        -231           13                   -17.77
203    Washington      2        -195           10                   -19.50
204    Washington      3         147            6                    24.50
205    Washington      4          55           10                     5.50
206    Washington      5         329           13                    25.31
207    Washington      6         739           14                    52.79
208    Washington      7         373           12                    31.08
209      Winnipeg      1        -246           15                   -16.40
210      Winnipeg      2        -295            9                   -32.78
211      Winnipeg      3         -83           13                    -6.38
212      Winnipeg      4         230           13                    17.69
213      Winnipeg      5         108            9                    12.00
214      Winnipeg      6         319           10                    31.90
215      Winnipeg      7         690           17                    40.59

The round breakdown reveals a consistent pattern across all teams — rounds 
1 through 3 are almost universally negative, while rounds 4 through 7 
produce increasingly large positive scores. This confirms the late round 
asymmetry identified in formula.ipynb: the metric rewards late round steals 
more than it penalizes early round busts, and the cumulative team rankings 
are heavily influenced by late round performance.

To supplement the main ranking, we produce a separate dataset restricted 
to rounds 1 through 3 — the picks where scouting skill is most scrutinized 
and where the late round asymmetry does not apply.

### Early Rounds Ranking — Rounds 1-3 Only

In [5]:
df_early = df[df['round'] <= 3]

team_rankings_early = df_early.groupby('drafted_by').agg(
    total_plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_rankings_early = team_rankings_early.sort_values('total_plus_minus', ascending=False).reset_index(drop=True)
team_rankings_early.index += 1
team_rankings_early = team_rankings_early.rename(columns={'drafted_by': 'team'})

print("NHL Team Draft Rankings 2005-2017 — Rounds 1-3 Only")
print(team_rankings_early.to_string())

NHL Team Draft Rankings 2005-2017 — Rounds 1-3 Only
            team  total_plus_minus  total_picks  avg_plus_minus_per_pick
1          Vegas               -17            6                    -2.83
2        Detroit              -128           37                    -3.46
3    Los Angeles              -129           35                    -3.69
4      Nashville              -135           36                    -3.75
5     New Jersey              -170           37                    -4.59
6     Pittsburgh              -205           28                    -7.32
7   Philadelphia              -251           33                    -7.61
8     Washington              -279           29                    -9.62
9       Carolina              -313           38                    -8.24
10     Minnesota              -331           27                   -12.26
11    NY Rangers              -373           33                   -11.30
12     Tampa Bay              -373           38                    -9.82
13     St. Louis              -390           42                    -9.29
14        Dallas              -396           34                   -11.65
15        Ottawa              -416           31                   -13.42
16      San Jose              -439           27                   -16.26
17        Boston              -501           35                   -14.31
18      Columbus              -542           36                   -15.06
19       Anaheim              -551           43                   -12.81
20      Montreal              -556           37                   -15.03
21       Calgary              -570           32                   -17.81
22      Edmonton              -597           40                   -14.92
23      Winnipeg              -624           37                   -16.86
24       Toronto              -625           33                   -18.94
25     Vancouver              -631           28                   -22.54
26      Colorado              -639           36                   -17.75
27       Florida              -673           41                   -16.41
28       Chicago              -702           46                   -15.26
29       Buffalo              -723           44                   -16.43
30  NY Islanders              -725           38                   -19.08
31       Arizona              -813           45                   -18.07

## Tableau Preparation

All outputs are saved to data/outputs/ for use in the Tableau dashboard.

In [6]:
# Export all CSVs
team_rankings.to_csv('../data/outputs/team_rankings.csv', index=False)
team_by_year.to_csv('../data/outputs/team_by_year.csv', index=False)
team_by_round.to_csv('../data/outputs/team_by_round.csv', index=False)
team_rankings_early.to_csv('../data/outputs/team_rankings_early.csv', index=False)

print("All files exported successfully!")
print(f"  team_rankings.csv       — {len(team_rankings)} rows")
print(f"  team_by_year.csv        — {len(team_by_year)} rows")
print(f"  team_by_round.csv       — {len(team_by_round)} rows")
print(f"  team_rankings_early.csv — {len(team_rankings_early)} rows")

All files exported successfully!
  team_rankings.csv       — 31 rows
  team_by_year.csv        — 391 rows
  team_by_round.csv       — 216 rows
  team_rankings_early.csv — 31 rows

## End of Analysis

In [7]:
print("Analysis complete.")

Analysis complete.

All datasets have been prepared and exported to data/outputs/. 
These files serve as the data source for the Tableau dashboard.