# NHL Draft Analysis

This notebook loads the draft scores produced by formula.ipynb, applies 
franchise consolidation, adds team colors, and exports clean CSVs for 
the Tableau dashboard.

## Setup

In [1]:
import pandas as pd

df = pd.read_csv('../data/outputs/draft_scores.csv')
print(f"Loaded {len(df)} rows")
df.head()

Loaded 2484 rows

,draft_year,round,pick_number,drafted_by,player_name,position,games_played,points,performance_score,hindsight_rank,plus_minus
0,2005,1,1,Pittsburgh,Sidney Crosby,C,1408.0,1746.0,5406.34,1,0
1,2005,1,2,Anaheim,Bobby Ryan,R,866.0,569.0,2169.01,9,-7
2,2005,1,3,Carolina,Jack Johnson,D,1228.0,342.0,2011.18,12,-9
3,2005,1,4,Minnesota,Benoit Pouliot,L,625.0,263.0,1227.27,21,-17
4,2005,1,6,Columbus,Gilbert Brule,C,299.0,95.0,516.55,39,-33

## Team Rankings

Overall team draft rankings from 2005 to 2017, measured by cumulative 
plus/minus across all picks and all drafts.

In [2]:
team_rankings = df.groupby('drafted_by').agg(
    total_plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_rankings = team_rankings.sort_values('total_plus_minus', ascending=False).reset_index(drop=True)
team_rankings.index += 1
team_rankings.columns = ['team', 'total_plus_minus', 'total_picks', 'avg_per_pick']

print("NHL Team Draft Rankings 2005-2017")
print(team_rankings.to_string())

NHL Team Draft Rankings 2005-2017
            team  total_plus_minus  total_picks  avg_per_pick
1       San Jose              4077           81         50.33
2    Los Angeles              3940           88         44.77
3        Detroit              3536           87         40.64
4      Tampa Bay              3382           86         39.33
5     Washington              3196           78         40.97
6        Chicago              3186          104         30.63
7        Toronto              3144           87         36.14
8     New Jersey              3127           84         37.23
9      Nashville              3079           85         36.22
10      Columbus              2927           85         34.44
11  Philadelphia              2871           78         36.81
12     Minnesota              2871           73         39.33
13    Pittsburgh              2815           71         39.65
14        Ottawa              2775           78         35.58
15  NY Islanders              2684           88         30.50
16      Winnipeg              2660           86         30.93
17        Boston              2640           78         33.85
18     Vancouver              2610           75         34.80
19       Calgary              2606           77         33.84
20       Buffalo              2589           92         28.14
21     St. Louis              2467           89         27.72
22    NY Rangers              2343           77         30.43
23      Carolina              2298           81         28.37
24      Montreal              2202           80         27.52
25        Dallas              2186           75         29.15
26      Edmonton              1923           86         22.36
27      Colorado              1921           79         24.32
28       Florida              1879           86         21.85
29       Anaheim              1650           78         21.15
30       Arizona              1513           82         18.45
31         Vegas               252           10         25.20

## Consistency Analysis

Team plus/minus broken down by draft year. Reveals whether a team's 
overall ranking is driven by consistent performance or a few standout 
draft classes.

In [3]:
team_by_year = df.groupby(['drafted_by', 'draft_year']).agg(
    plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_by_year = team_by_year.rename(columns={'drafted_by': 'team'})

print(f"team_by_year shape: {team_by_year.shape}")
team_by_year.head(20)

team_by_year shape: (391, 5)

       team  draft_year  plus_minus  total_picks  avg_plus_minus_per_pick
0   Anaheim        2005           6            5                     1.20
1   Anaheim        2006          89            5                    17.80
2   Anaheim        2007          14            6                     2.33
3   Anaheim        2008         119            9                    13.22
4   Anaheim        2009          74            6                    12.33
5   Anaheim        2010         370            8                    46.25
6   Anaheim        2011         205            6                    34.17
7   Anaheim        2012         249            7                    35.57
8   Anaheim        2013          84            5                    16.80
9   Anaheim        2014         218            5                    43.60
10  Anaheim        2015          78            6                    13.00
11  Anaheim        2016         139            6                    23.17
12  Anaheim        2017           5            4                     1.25
13  Arizona        2005         257            4                    64.25
14  Arizona        2006         349            7                    49.86
15  Arizona        2007         -82            5                   -16.40
16  Arizona        2008          95            8                    11.88
17  Arizona        2009          14            5                     2.80
18  Arizona        2010         -93            3                   -31.00
19  Arizona        2011           3            8                     0.38

## Round Analysis

Team plus/minus broken down by draft round. Reveals whether certain 
teams excel at finding late round steals or consistently capitalize 
on early round picks.

In [4]:
team_by_round = df.groupby(['drafted_by', 'round']).agg(
    plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_by_round = team_by_round.rename(columns={'drafted_by': 'team'})

print(f"team_by_round shape: {team_by_round.shape}")
team_by_round.head(20)
print(team_by_round.to_string())

team_by_round shape: (216, 5)
             team  round  plus_minus  total_picks  avg_plus_minus_per_pick
0         Anaheim      1        -232           15                   -15.47
1         Anaheim      2        -270           16                   -16.88
2         Anaheim      3         -47           12                    -3.92
3         Anaheim      4         270           10                    27.00
4         Anaheim      5         624           12                    52.00
5         Anaheim      6         595            7                    85.00
6         Anaheim      7         710            6                   118.33
7         Arizona      1        -402           18                   -22.33
8         Arizona      2        -294           13                   -22.62
9         Arizona      3        -108           14                    -7.71
10        Arizona      4         231            9                    25.67
11        Arizona      5         606           11                    55.09
12        Arizona      6         353            6                    58.83
13        Arizona      7        1127           11                   102.45
14         Boston      1        -302           14                   -21.57
15         Boston      2        -262           15                   -17.47
16         Boston      3          63            6                    10.50
17         Boston      4         285            9                    31.67
18         Boston      5         613           11                    55.73
19         Boston      6         942           11                    85.64
20         Boston      7        1301           12                   108.42
21        Buffalo      1        -296           15                   -19.73
22        Buffalo      2        -362           15                   -24.13
23        Buffalo      3         -65           14                    -4.64
24        Buffalo      4         304           10                    30.40
25        Buffalo      5         640           14                    45.71
26        Buffalo      6         708            8                    88.50
27        Buffalo      7        1660           16                   103.75
28        Calgary      1        -348           12                   -29.00
29        Calgary      2        -112            8                   -14.00
30        Calgary      3         -92           12                    -7.67
31        Calgary      4         470           12                    39.17
32        Calgary      5         413            9                    45.89
33        Calgary      6         849           10                    84.90
34        Calgary      7        1426           14                   101.86
35       Carolina      1        -271           12                   -22.58
36       Carolina      2          11           13                     0.85
37       Carolina      3         -39           13                    -3.00
38       Carolina      4         390           14                    27.86
39       Carolina      5         477           10                    47.70
40       Carolina      6         781           10                    78.10
41       Carolina      7         949            9                   105.44
42        Chicago      1        -187           12                   -15.58
43        Chicago      2        -433           19                   -22.79
44        Chicago      3         -85           15                    -5.67
45        Chicago      4         485           15                    32.33
46        Chicago      5         775           14                    55.36
47        Chicago      6        1390           17                    81.76
48        Chicago      7        1241           12                   103.42
49       Colorado      1        -222           11                   -20.18
50       Colorado      2        -421           17                   -24.76
51       Colorado      3           6            8                     0.75
52       Colorado      4         164           11                    14.91
53       Colorado      5         465            9                    51.67
54       Colorado      6         746           11                    67.82
55       Colorado      7        1183           12                    98.58
56       Columbus      1        -320           14                   -22.86
57       Columbus      2        -322           14                   -23.00
58       Columbus      3         100            8                    12.50
59       Columbus      4         451           12                    37.58
60       Columbus      5         611           13                    47.00
61       Columbus      6        1099           12                    91.58
62       Columbus      7        1308           12                   109.00
63         Dallas      1        -310           11                   -28.18
64         Dallas      2         -92           12                    -7.67
65         Dallas      3          17           11                     1.55
66         Dallas      4         248            9                    27.56
67         Dallas      5        1197           19                    63.00
68         Dallas      6         612            8                    76.50
69         Dallas      7         514            5                   102.80
70        Detroit      1         -96            8                   -12.00
71        Detroit      2         -11           16                    -0.69
72        Detroit      3         -26           13                    -2.00
73        Detroit      4         333            9                    37.00
74        Detroit      5         676           13                    52.00
75        Detroit      6        1016           13                    78.15
76        Detroit      7        1644           15                   109.60
77       Edmonton      1        -170           15                   -11.33
78       Edmonton      2        -278           10                   -27.80
79       Edmonton      3        -149           15                    -9.93
80       Edmonton      4         344           16                    21.50
81       Edmonton      5         459           11                    41.73
82       Edmonton      6         859           11                    78.09
83       Edmonton      7         858            8                   107.25
84        Florida      1        -221           14                   -15.79
85        Florida      2        -399           12                   -33.25
86        Florida      3         -53           15                    -3.53
87        Florida      4         286           16                    17.88
88        Florida      5         404            9                    44.89
89        Florida      6         843           11                    76.64
90        Florida      7        1019            9                   113.22
91    Los Angeles      1         -69           10                    -6.90
92    Los Angeles      2        -163           14                   -11.64
93    Los Angeles      3         103           11                     9.36
94    Los Angeles      4         579           13                    44.54
95    Los Angeles      5         847           14                    60.50
96    Los Angeles      6         863           11                    78.45
97    Los Angeles      7        1780           15                   118.67
98      Minnesota      1        -253           12                   -21.08
99      Minnesota      2        -107           10                   -10.70
100     Minnesota      3          29            5                     5.80
101     Minnesota      4         302           12                    25.17
102     Minnesota      5         578            9                    64.22
103     Minnesota      6         734           10                    73.40
104     Minnesota      7        1588           15                   105.87
105      Montreal      1        -279           12                   -23.25
106      Montreal      2        -185           11                   -16.82
107      Montreal      3         -92           14                    -6.57
108      Montreal      4         113           10                    11.30
109      Montreal      5         712           14                    50.86
110      Montreal      6         666            8                    83.25
111      Montreal      7        1267           11                   115.18
112  NY Islanders      1        -271           15                   -18.07
113  NY Islanders      2        -199            9                   -22.11
114  NY Islanders      3        -255           14                   -18.21
115  NY Islanders      4         422           13                    32.46
116  NY Islanders      5         579           12                    48.25
117  NY Islanders      6        1191           13                    91.62
118  NY Islanders      7        1217           12                   101.42
119    NY Rangers      1        -186           10                   -18.60
120    NY Rangers      2        -107            8                   -13.38
121    NY Rangers      3         -75           15                    -5.00
122    NY Rangers      4         339           12                    28.25
123    NY Rangers      5         601           14                    42.93
124    NY Rangers      6         910           10                    91.00
125    NY Rangers      7         861            8                   107.62
126     Nashville      1        -115            9                   -12.78
127     Nashville      2        -139           13                   -10.69
128     Nashville      3         119           14                     8.50
129     Nashville      4         444           15                    29.60
130     Nashville      5         528           10                    52.80
131     Nashville      6         999           13                    76.85
132     Nashville      7        1243           11                   113.00
133    New Jersey      1        -236           10                   -23.60
134    New Jersey      2         -86           11                    -7.82
135    New Jersey      3         152           16                     9.50
136    New Jersey      4         360           12                    30.00
137    New Jersey      5         635           10                    63.50
138    New Jersey      6        1015           13                    78.08
139    New Jersey      7        1287           12                   107.25
140        Ottawa      1        -287           14                   -20.50
141        Ottawa      2        -164            9                   -18.22
142        Ottawa      3          35            8                     4.38
143        Ottawa      4         652           18                    36.22
144        Ottawa      5         565            9                    62.78
145        Ottawa      6         733            9                    81.44
146        Ottawa      7        1241           11                   112.82
147  Philadelphia      1        -164           13                   -12.62
148  Philadelphia      2        -231            9                   -25.67
149  Philadelphia      3         144           11                    13.09
150  Philadelphia      4         215           11                    19.55
151  Philadelphia      5         603           10                    60.30
152  Philadelphia      6        1120           13                    86.15
153  Philadelphia      7        1184           11                   107.64
154    Pittsburgh      1        -226            9                   -25.11
155    Pittsburgh      2        -212            9                   -23.56
156    Pittsburgh      3         233           10                    23.30
157    Pittsburgh      4         304           10                    30.40
158    Pittsburgh      5         667           12                    55.58
159    Pittsburgh      6        1082           13                    83.23
160    Pittsburgh      7         967            8                   120.88
161      San Jose      1        -154           10                   -15.40
162      San Jose      2        -184           12                   -15.33
163      San Jose      3        -101            5                   -20.20
164      San Jose      4         156            7                    22.29
165      San Jose      5         960           16                    60.00
166      San Jose      6        1336           14                    95.43
167      San Jose      7        2064           17                   121.41
168     St. Louis      1         -44           15                    -2.93
169     St. Louis      2        -392           17                   -23.06
170     St. Louis      3          46           10                     4.60
171     St. Louis      4         271           14                    19.36
172     St. Louis      5         449            9                    49.89
173     St. Louis      6        1112           14                    79.43
174     St. Louis      7        1025           10                   102.50
175     Tampa Bay      1        -208           11                   -18.91
176     Tampa Bay      2        -236           14                   -16.86
177     Tampa Bay      3          71           13                     5.46
178     Tampa Bay      4         404           12                    33.67
179     Tampa Bay      5         316            6                    52.67
180     Tampa Bay      6        1150           13                    88.46
181     Tampa Bay      7        1885           17                   110.88
182       Toronto      1        -234           11                   -21.27
183       Toronto      2        -308           11                   -28.00
184       Toronto      3         -83           11                    -7.55
185       Toronto      4         244           11                    22.18
186       Toronto      5         727           15                    48.47
187       Toronto      6        1227           15                    81.80
188       Toronto      7        1571           13                   120.85
189     Vancouver      1        -419           14                   -29.93
190     Vancouver      2        -192            7                   -27.43
191     Vancouver      3         -17            7                    -2.43
192     Vancouver      4          84            7                    12.00
193     Vancouver      5         806           14                    57.57
194     Vancouver      6        1000           13                    76.92
195     Vancouver      7        1348           13                   103.69
196         Vegas      1         -32            3                   -10.67
197         Vegas      2          11            2                     5.50
198         Vegas      3           4            1                     4.00
199         Vegas      5          83            2                    41.50
200         Vegas      6          65            1                    65.00
201         Vegas      7         121            1                   121.00
202    Washington      1        -231           13                   -17.77
203    Washington      2        -195           10                   -19.50
204    Washington      3         147            6                    24.50
205    Washington      4         184           10                    18.40
206    Washington      5         716           13                    55.08
207    Washington      6        1289           14                    92.07
208    Washington      7        1286           12                   107.17
209      Winnipeg      1        -246           15                   -16.40
210      Winnipeg      2        -295            9                   -32.78
211      Winnipeg      3         -82           13                    -6.31
212      Winnipeg      4         292           13                    22.46
213      Winnipeg      5         335            9                    37.22
214      Winnipeg      6         784           10                    78.40
215      Winnipeg      7        1872           17                   110.12

The round breakdown reveals a consistent pattern across all teams — rounds 
1 through 3 are almost universally negative, while rounds 4 through 7 
produce increasingly large positive scores. This confirms the late round 
asymmetry identified in formula.ipynb: the metric rewards late round steals 
more than it penalizes early round busts, and the cumulative team rankings 
are heavily influenced by late round performance.

To supplement the main ranking, we produce a separate dataset restricted 
to rounds 1 through 3 — the picks where scouting skill is most scrutinized 
and where the late round asymmetry does not apply.

### Early Rounds Ranking — Rounds 1-3 Only

In [5]:
df_early = df[df['round'] <= 3]

team_rankings_early = df_early.groupby('drafted_by').agg(
    total_plus_minus=('plus_minus', 'sum'),
    total_picks=('plus_minus', 'count'),
    avg_plus_minus_per_pick=('plus_minus', 'mean')
).round(2).reset_index()

team_rankings_early = team_rankings_early.sort_values('total_plus_minus', ascending=False).reset_index(drop=True)
team_rankings_early.index += 1
team_rankings_early = team_rankings_early.rename(columns={'drafted_by': 'team'})

print("NHL Team Draft Rankings 2005-2017 — Rounds 1-3 Only")
print(team_rankings_early.to_string())

NHL Team Draft Rankings 2005-2017 — Rounds 1-3 Only
            team  total_plus_minus  total_picks  avg_plus_minus_per_pick
1          Vegas               -17            6                    -2.83
2    Los Angeles              -129           35                    -3.69
3        Detroit              -133           37                    -3.59
4      Nashville              -135           36                    -3.75
5     New Jersey              -170           37                    -4.59
6     Pittsburgh              -205           28                    -7.32
7   Philadelphia              -251           33                    -7.61
8     Washington              -279           29                    -9.62
9       Carolina              -299           38                    -7.87
10     Minnesota              -331           27                   -12.26
11    NY Rangers              -368           33                   -11.15
12     Tampa Bay              -373           38                    -9.82
13        Dallas              -385           34                   -11.32
14     St. Louis              -390           42                    -9.29
15        Ottawa              -416           31                   -13.42
16      San Jose              -439           27                   -16.26
17        Boston              -501           35                   -14.31
18      Columbus              -542           36                   -15.06
19       Anaheim              -549           43                   -12.77
20       Calgary              -552           32                   -17.25
21      Montreal              -556           37                   -15.03
22      Edmonton              -597           40                   -14.92
23      Winnipeg              -623           37                   -16.84
24       Toronto              -625           33                   -18.94
25     Vancouver              -628           28                   -22.43
26      Colorado              -637           36                   -17.69
27       Florida              -673           41                   -16.41
28       Chicago              -705           46                   -15.33
29       Buffalo              -723           44                   -16.43
30  NY Islanders              -725           38                   -19.08
31       Arizona              -804           45                   -17.87

## Tableau Preparation

All outputs are saved to data/outputs/ for use in the Tableau dashboard.

In [6]:
# Export all CSVs
team_rankings.to_csv('../data/outputs/team_rankings_initial.csv', index=False)
team_by_year.to_csv('../data/outputs/team_by_year_initial.csv', index=False)
team_by_round.to_csv('../data/outputs/team_by_round_initial.csv', index=False)
team_rankings_early.to_csv('../data/outputs/team_rankings_early_initial.csv', index=False)
df.to_csv('../data/outputs/draft_scores_pre_fix.csv', index=False)

print("All files exported successfully!")
print(f"  team_rankings_initial.csv      — {len(team_rankings)} rows")
print(f"  team_by_year_initial.csv       — {len(team_by_year)} rows")
print(f"  team_by_round_initial.csv      — {len(team_by_round)} rows")
print(f"  team_rankings_early_initial.csv — {len(team_rankings_early)} rows")
print(f"  draft_scores_pre_fix.csv         — {len(df)} rows")

All files exported successfully!
  team_rankings_initial.csv      — 31 rows
  team_by_year_initial.csv       — 391 rows
  team_by_round_initial.csv      — 216 rows
  team_rankings_early_initial.csv — 31 rows
  draft_scores_pre_fix.csv         — 2484 rows

## End of Analysis

In [7]:
print("Analysis complete.")

Analysis complete.

All datasets have been prepared and exported to data/outputs/. 
These files serve as the data source for the Tableau dashboard.